# .travis.yml for use with EPICS Base ci-scripts
# (see: https://github.com/epics-base/ci-scripts)

language: cpp
compiler: gcc
dist: xenial

cache:
  directories:
  - $HOME/.cache

env:
  global:
    - SETUP_PATH=.ci-local:.ci
    - EXTRA="CMD_CXXFLAGS=-std=c++11"
    - BASE_RECURSIVE=NO

addons:
  apt:
    packages:
    # for all EPICS builds
    - libreadline6-dev
    - libncurses5-dev
    - perl
    # for clang compiler
    - clang
    # for RTEMS cross builds
    - g++-mingw-w64-i686
    - qemu-system-x86
  homebrew:
    packages:
    # for all EPICS builds
    - bash
    update: true

install:
  - python .ci/cue.py prepare

script:
  - python .ci/cue.py build
  - python .ci/cue.py test
  - python .ci/cue.py test-results


# Define build jobs

# Well-known variables to use
# SET         source setup file
# ADD_MODULES extra modules (for a specific job)
# BCFG        build configuration (static/debug/static-debug;
#             default: shared-optimized)
# TEST        set to NO to skip running the tests (default: YES)
# VV          set to make build scripts verbose (default: unset)
# EXTRA       content will be added to make command line
# EXTRA1..5   more additional arguments for the make command
#             (one argument per variable)

# Usually from setup files, but may be specified or overridden
#  on a job line
# MODULES     list of dependency modules
# BASE        branch or release tag name of the EPICS Base to use
# <MODULE>    branch or release tag for a specific module
# ...         see README for setup file syntax description

jobs:
  include:

# Different configurations of default gcc and clang

  - env: BASE=7.0

  - env: BASE=7.0
    compiler: clang

  - env: BASE=7.0 BCFG=static

  - env: BASE=3.15

  - env: BASE=3.15 BCFG=static

  - env: BASE=R3.15.3

  - env: BASE=R3.15.3 BCFG=static

  - env: BASE=R3.14.12.8

  - env: BASE=R3.14.12.8 BCFG=static

# Trusty: compiler versions very close to RHEL 7

  - env: BASE=7.0
    dist: trusty

  - env: BASE=7.0 BCFG=static
    dist: trusty

# Cross-compilation to RTEMS 4.x doesn't work (g++ 4.4.x is too old)
#  - env: BASE=R3.16.2 RTEMS=4.10 EXTRA="CMD_CXXFLAGS=-std=c++0x"
#  - env: BASE=R3.16.2 RTEMS=4.9 EXTRA="CMD_CXXFLAGS=-std=c++0x"

# MacOS build

  - env: BASE=3.15
    os: osx
    compiler: clang

# Windows builds

  - env: BASE=7.0
    os: windows
    compiler: vs2017

  - env: BASE=7.0 BCFG=static
    os: windows
    compiler: vs2017

  - env: BASE=R3.15.3
    os: windows
    compiler: vs2017

  - env: BASE=7.0
    os: windows
